#!/usr/bin/env bash
set -e -o pipefail

# Add repo specific metadata here.

PACKAGE_NAME="pyenv"
RELEASE_PACKAGE_NAME="Python"
RELEASE_PACKAGE_VERSION_CONFIG_KEY="IMAGE_PYTHON_VERSION"
RELEASE_TAG_PACKAGE_NAME="python"
RELEASE_USE_CUSTOM_RELEASE_VERSION="y"
BASE_IMAGE_CONFIG_KEY_PREFIX="BASE_IMAGE"
UPSTREAM_VERSION_CONFIG_KEY="PYENV_VERSION"
UPSTREAM_CHECKSUM_CONFIG_KEY="PYENV_SHA256_CHECKSUM"
UPSTREAM_GIT_REPO="https://github.com/pyenv/pyenv"
TEST_TYPE="background"
TEST_CONTAINER_TYPE="python-base"
TEST_CONTAINER_START_WAIT_SECONDS="10"

current_upstream_version() {
    get_config_arg ${UPSTREAM_VERSION_CONFIG_KEY:?}
}

latest_upstream_version() {
    git_remote_repo_latest_tag "${UPSTREAM_GIT_REPO:?}.git"
}

update_latest_upstream_version() {
    local cur_ver="${1:?}"
    local latest_ver="${2:?}"
    local sha256_checksum="$(upstream_github_repo_archive_sha256_checksum ${latest_ver:?})"
    echo "Updating ${PACKAGE_NAME:?} ${UPSTREAM_VERSION_CONFIG_KEY:?} '${cur_ver:?}' -> '${latest_ver:?}'"
    set_config_arg "${UPSTREAM_VERSION_CONFIG_KEY:?}" "${latest_ver:?}"
    set_config_arg "${UPSTREAM_CHECKSUM_CONFIG_KEY:?}" "${sha256_checksum:?}"
    git add ${ARGS_FILE:?}
}

custom_release_version() {
    echo -n "v$(latest_base_image_tag)"
}

package_current_release_version() {
    get_config_arg "${RELEASE_PACKAGE_VERSION_CONFIG_KEY:?}"
}

test_start_container() {
    local container_name="${1:?}"
    docker run \
        --name ${container_name:?} \
        --detach \
        --rm \
        --publish 127.0.0.1:8082:8082 \
        ${IMAGE:?} \
        python3 -m http.server 8082
}

test_image_after_container_startup() {
    local container_name="${1:?}"

    set +e
    local http_status_code=$(\
        curl -w "%{http_code}" --silent --output /dev/null --location http://127.0.0.1:8082/)
    local return_code=$?
    set -e

    if [[ $return_code != "0" ]]; then
        echo "Test failed: Obtained non-zero return code"
        echo "Output: ${http_status_code}"
        echo "Return Code: ${return_code}"
        test_cleanup_container ${container_name:?}
        exit 1
    fi
    if [[ ${http_status_code:?} != "200" ]]; then
        echo "Test failed: Status code is not 200"
        echo "Output: ${http_status_code}"
        echo "Return Code: ${return_code}"
        test_cleanup_container ${container_name:?}
        exit 1
    fi
}
