#!/usr/bin/env bash
set -e -o pipefail

# Add repo specific metadata here.

UPSTREAM_IMAGE_CONFIG_KEY_PREFIX="BASE_IMAGE"
TEST_TYPE="background"
TEST_CONTAINER_TYPE="python-base"
TEST_CONTAINER_START_WAIT_SECONDS="10"

test_start_container() {
    local container_name="${1:?}"

    docker run \
        --name ${container_name:?} \
        --detach \
        --rm \
        --publish 127.0.0.1:8082:8082 \
        ${IMAGE:?} \
        python3 -m http.server 8082
}

test_image_after_container_startup() {
    local container_name="${1:?}"

    set +e
    local http_status_code=$(\
        curl -w "%{http_code}" --silent --output /dev/null --location http://127.0.0.1:8082/)
    local return_code=$?
    set -e

    if [[ $return_code != "0" ]]; then
        echo "Test failed: Obtained non-zero return code"
        echo "Output: ${http_status_code}"
        echo "Return Code: ${return_code}"
        test_cleanup_container ${container_name:?}
        exit 1
    fi
    if [[ ${http_status_code:?} != "200" ]]; then
        echo "Test failed: Status code is not 200"
        echo "Output: ${http_status_code}"
        echo "Return Code: ${return_code}"
        test_cleanup_container ${container_name:?}
        exit 1
    fi
}
