#!/usr/bin/env bash
set -e -o pipefail

# Add repo specific metadata here.

BASE_IMAGE_CONFIG_KEY_PREFIX="BASE_IMAGE"

UPSTREAM_PACKAGE_NAME="pyenv"
UPSTREAM_VERSION_CONFIG_KEY="PYENV_VERSION"
UPSTREAM_CHECKSUM_CONFIG_KEY="PYENV_SHA256_CHECKSUM"
UPSTREAM_GIT_REPO="https://github.com/pyenv/pyenv"

RELEASE_PACKAGE_NAME="Python"
RELEASE_PACKAGE_VERSION_CONFIG_KEY="IMAGE_PYTHON_VERSION"
RELEASE_TAG_PACKAGE_NAME="python"
RELEASE_USE_CUSTOM_RELEASE_VERSION="y"

TEST_TYPE="background"
TEST_CONTAINER_TYPE="python-base"
TEST_CONTAINER_START_WAIT_SECONDS="10"

current_upstream_version() {
    get_config_arg ${UPSTREAM_VERSION_CONFIG_KEY:?}
}

latest_upstream_version() {
    git_remote_repo_latest_tag "${UPSTREAM_GIT_REPO:?}.git"
}

update_latest_upstream_version() {
    local cur_ver="${1:?}"
    local latest_ver="${2:?}"
    local sha256_checksum="$(upstream_github_repo_archive_sha256_checksum ${latest_ver:?})"
    echo "Updating ${PACKAGE_NAME:?} ${UPSTREAM_VERSION_CONFIG_KEY:?} '${cur_ver:?}' -> '${latest_ver:?}'"
    set_config_arg "${UPSTREAM_VERSION_CONFIG_KEY:?}" "${latest_ver:?}"
    set_config_arg "${UPSTREAM_CHECKSUM_CONFIG_KEY:?}" "${sha256_checksum:?}"
    git add ${ARGS_FILE:?}
}

custom_release_version() {
    echo -n "v$(latest_base_image_tag)"
}

package_current_release_version() {
    get_config_arg "${RELEASE_PACKAGE_VERSION_CONFIG_KEY:?}"
}

test_start_container() {
    local container_name="${1:?}"
    docker run \
        --name ${container_name:?} \
        --detach \
        --rm \
        --publish 127.0.0.1:8082:8082 \
        ${IMAGE:?} \
        python3 -m http.server 8082
}

test_image_after_container_startup() {
    local container_name="${1:?}"
    test_http_endpoint "${container_name:?}" http 127.0.0.1 8082
}
